title: Portfolio
description: Portfolio das aulas de aplicações informáticas
author: Pedro Almeida
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - aulas/template_aula.md
  - aplicacoes.txt
