title: Portfolio
description: Portfolio de aplicações informáticas
url: "https://1pedroalmeida.github.io"

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: aleen42/markdown-only
exclude:
  aplicacoes.txt
